project_id = "tookphxcguqlyoyzpjwu"

[functions.entra-token-exchange]
verify_jwt = false

[functions.get-entra-config]
verify_jwt = false

[functions.entra-link-account]
verify_jwt = false

[functions.wia-auth]
verify_jwt = false
